### ISSUE TITLE
Pseudo-element selectors improperly minified

### ISSUE THREAD

**Issue by hamaluik** [Mnwa/css-minify#6]
It seems that [psuedo-element](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements) selectors aren't being properly minified. Essentially, any selectors that begin with `::` get the double colons minified to a single one `:`, which changes / invalidates the selector.

I came across this when using the `::backdrop` psuedo-element. I would expect the following:

```css
dialog::backdrop {
  backdrop-filter: blur(4px);
}
```

to minify down to:

```css
dialog::backdrop{backdrop-filter:blur(4px)}
```

however, it instead minifies down to:

```css
dialog:backdrop {backdrop-filter:blur(4px)}
```

(note the single `:`, which makes the selector not work at all. This happens across _all_ of the optimization levels (Zero included).
