### ISSUE TITLE
CSS compress incorrect when both set `background-color` and `background-image`

### ISSUE THREAD

**Issue by TakWolf** [Mnwa/css-minify#7]
Raising from: https://github.com/wilsonzlin/minify-html/issues/132

Optimization level >= 2

Raw css:

```css
        body {
            background-color: #3cb03c;
            background-image: linear-gradient(45deg, limegreen 25%, transparent 25%, transparent 75%, limegreen 75%), linear-gradient(-45deg, limegreen 25%, transparent 25%, transparent 75%, limegreen 75%);
            background-size: 128px 128px;
            background-attachment: fixed;
        }
```

Output css: (has been reformated)

```css
    body {
        background: #3cb03c;
        background-size: 128px 128px
    }
```

It seem that background-color replace background-image, but them can be set both.

https://css-tricks.com/css-basics-using-multiple-backgrounds
